/**
 * 敏感词哈希生成脚本（手动运行：pnpm gen:sensitive-words）
 *
 * 读 secrets/sensitive-words.txt + SENSITIVE_WORDS_HMAC_KEY（env 优先，
 * 项目根 .dev.vars 作为 fallback），输出 src/workers/sensitiveWordHashes.generated.ts。
 *
 * 不打印任何词、哈希、key；只在控制台输出条目数概览或空表提示。
 */

import { createHmac } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const TXT_PATH = resolve(ROOT, 'secrets/sensitive-words.txt')
const OUT_PATH = resolve(ROOT, 'src/workers/sensitiveWordHashes.generated.ts')
const DEV_VARS_PATH = resolve(ROOT, '.dev.vars')
const FINGERPRINT_MAGIC = 'sensitive-words-fingerprint-v1'
const KEY_NAME = 'SENSITIVE_WORDS_HMAC_KEY'

function readDevVars(path: string): Record<string, string> {
  if (!existsSync(path)) return {}
  const out: Record<string, string> = {}
  for (const raw of readFileSync(path, 'utf-8').split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq < 0) continue
    const k = line.slice(0, eq).trim()
    const v = line
      .slice(eq + 1)
      .trim()
      .replace(/^['"]|['"]$/g, '')
    out[k] = v
  }
  return out
}

function loadKey(): string {
  const fromEnv = process.env[KEY_NAME]
  if (fromEnv && fromEnv.length > 0) return fromEnv
  const fromDevVars = readDevVars(DEV_VARS_PATH)[KEY_NAME]
  if (fromDevVars && fromDevVars.length > 0) return fromDevVars
  console.error(
    `Error: ${KEY_NAME} not set in env or ${DEV_VARS_PATH}. ` +
      `Generate one: openssl rand -base64 32`
  )
  process.exit(1)
}

function hashTrunc(key: string, input: string): string {
  return createHmac('sha256', key).update(input).digest().subarray(0, 16).toString('base64')
}

function loadWords(path: string): string[] | null {
  if (!existsSync(path)) return null
  const seen = new Set<string>()
  for (const raw of readFileSync(path, 'utf-8').split(/\r?\n/)) {
    const line = raw.trim().toLowerCase()
    if (!line || line.startsWith('#')) continue
    seen.add(line)
  }
  return [...seen]
}

function buildModule(hashesByLength: Map<number, string[]>, fingerprint: string): string {
  const lengths = [...hashesByLength.keys()].sort((a, b) => a - b)
  const lines: string[] = []
  lines.push('// AUTO-GENERATED by scripts/buildSensitiveWords.ts. DO NOT EDIT.')
  lines.push('// Run `pnpm gen:sensitive-words` to regenerate.')
  lines.push('')
  lines.push('export const HASHES: ReadonlyMap<number, ReadonlySet<string>> = new Map([')
  for (const L of lengths) {
    const sorted = [...(hashesByLength.get(L) ?? [])].sort()
    const entries = sorted.map(h => `'${h}'`).join(', ')
    lines.push(`  [${L}, new Set([${entries}])],`)
  }
  lines.push('])')
  lines.push('')
  lines.push(`export const LENGTHS: readonly number[] = [${lengths.join(', ')}]`)
  lines.push('')
  lines.push(`export const KEY_FINGERPRINT: string = '${fingerprint}'`)
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  const key = loadKey()
  const fingerprint = hashTrunc(key, FINGERPRINT_MAGIC)
  const words = loadWords(TXT_PATH)

  if (words === null) {
    writeFileSync(OUT_PATH, buildModule(new Map(), fingerprint))
    console.log('Sensitive word file not found, generated empty table')
    return
  }

  const hashesByLength = new Map<number, string[]>()
  for (const word of words) {
    const L = word.length
    const arr = hashesByLength.get(L) ?? []
    arr.push(hashTrunc(key, word))
    hashesByLength.set(L, arr)
  }

  writeFileSync(OUT_PATH, buildModule(hashesByLength, fingerprint))
  console.log(`Generated ${words.length} hashes across ${hashesByLength.size} length buckets`)
}

main()
